name = "StatisticalManifolds"
uuid = "2d59fa81-9b3b-42d2-bf16-c012499602ea"
authors = ["Jacob T. Crosser"]
version = "0.1.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
